# Generated by Django 5.2.5 on 2025-09-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_booking_date_remove_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
