# Generated by Django 5.2.5 on 2025-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True, help_text='Optional bullet-pointed list of details for the booking', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('Card', 'Card'), ('Bkash', 'Bkash')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
