# Generated by Django 5.2.5 on 2025-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_details_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Bkash', 'Bkash')], default='Card', max_length=20),
        ),
    ]
