# Generated by Django 5.2.5 on 2025-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
