# Generated by Django 5.2.5 on 2025-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_booking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Not Accepted', 'Not Accepted'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Refunded', 'Refunded'), ('Refunded But Pending', 'Refunded But Pending'), ('Refunded But Rejected', 'Refunded But Rejected')], default='Not Accepted', max_length=30),
        ),
    ]
