# Generated by Django 5.2.5 on 2025-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Set after payment success (e.g. Visa, Master, Bkash, Nagad, etc.)', max_length=100, null=True),
        ),
    ]
